language: go

go:
  - 1.15.x

install:
  - go get -v -t -d ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN"

env:
  global:
    secure: qMrDUzm3at+jiB/D/a5pZmgpwrmfI1wvFSyPWL0NwfrxNdicHbMw0QoSBUQPtLaLedNSUD8cty7/lFyYuBUw+Ttb9zIBry5ucRvuQs1BIt3/byPKHs9sUHjoSUi4fi8DtxvXQ9L9wDbygQA+apGAEYIVGq1FN7gbtXwd/ryCECMV+NkaDbW0Rbw7AWMb4FohdevuTixurp1eHhzft+PzfSO1QgdLHux+rvx+qAVLzgoLZQNq2HkT0BIZoEHyGExZH8NIVXnMpWTS60k4bEhkwlD5fF80dQUrnLBLj1A6SWYU41vcizlbyKOr4Hemjm6TMD6ucs7ENxj2c5VLCtaFEDyewaJXytEiDzzlvLd+mk1dsdhfIGLDzAmEQvI2Gv2AesON7QuBG59OTZONQeAi//pXo9Gja7q6uQsDKfECwSln3C2/jz6NLb2/9i50CrJtN0Kc1KJauq6inp/nzr1ZGXmFzMhNoXm8XXoDgLpCuUrXQkMBrEfnXOGFZWFUK53Ath7E+1SuEyPchCxTr2gptaYXmzMcXz3ydUYi6MaYs2rffKZVW9jXYJr4PXGFEIe4koKaJAFelZVh6PtVfPYXS3JzMMc3zs151O9RblJCtJVrwkw3BlWYHs8Jz1IcGIlFuHKgp7CA5rEIAXdqJ67CKk+YIiaYTyt5HO22u+o65Ho=
